### ISSUE TITLE
Improve behaviour for stopwords-only search (e.g., »habe nun«) 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#595] opened 2022-09-23 07:40 UTC
https://dev.faustedition.net/search?q=habe+nun

applies to dev and non-dev, FF and Chrome

**Comment by thvitt** [comment] 2022-09-23 07:53
Search is fine, but both 'habe' and 'nun' are stop words.

Try ["habe nun" in the _alle Wortformen_ index](https://dev.faustedition.net/search?q=%22habe+nun%22&index=text)

**Comment by gerritbruening** [comment] 2022-09-23 08:04
> Search is fine, but both 'habe' and 'nun' are stop words.

This is surprising

**Comment by thvitt** [comment] 2022-09-23 08:15
Need to look which list is really used, but [this is a quite common one](https://github.com/stopwords-iso/stopwords-de).

Maybe generate a message when we're using stopwords and the query consists of stopwords only

**Comment by thvitt** [comment] 2022-09-23 14:04
also cf. https://github.com/faustedition/faust-gen-html/issues/623

**Comment by thvitt** [comment] 2022-09-23 14:06
Duplicate of https://github.com/faustedition/faust-gen-html/issues/623 actually

**Closed by thvitt** 2022-09-23 14:06 UTC
Labels: c:search, c:usability
