### ISSUE TITLE
ToC Faust II: "Saal des Thrones"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#158] opened 2016-07-15 16:50 UTC
See http://dev.faustedition.net/print/faust2.

Should be "Kaiserliche Pfalz".

**Comment by thvitt** [comment] 2016-07-15 18:21
It's not a bug, it's a <del>feature</del> design decision :-)

Both TOC and breadcrumbs use the scene labels that are defined [in the scene/line mapping](https://github.com/faustedition/faust-web/blob/master/data/scene_line_mapping.js). What else should be used? 

I'm currently [globally defining scene / act labels](https://github.com/faustedition/faust-gen-html/blob/master/xslt/add-metadata.xsl#L134) when enriching the transcripts, the intention is to use this everywhere (search, breadcrumbs, TOC, bargraph etc). If you want a different heading here, we need criteria …

**Comment by gerritbruening** [comment] 2016-07-25 14:36
Ideally, the ToC would be analogous to `genesis_faust_ii`.

If we go only one level below `div type="act"`, the correct heading would be "Kaiserliche Pfalz". If we enclude the subscenes as we do in `genesis_faust_ii`, we would need five headings:
* "Saal des Thrones"
* "Weitläufiger Saal"
* and so on

**Comment by thvitt** [comment] 2016-07-25 15:22
In its current state, this bug report does not enable me to do something sensible about it.

The whole sectioning stuff basically boils down to running _every_ textual transcript through the [code starting at f:section-div in add-metadata.xsl](https://github.com/faustedition/faust-gen-html/blob/master/xslt/add-metadata.xsl#L127). The rules there add some attributes to the `<div>`s that are used for splitting, TOC, breadcrumbs etc. at later stages:

* `f:section` determines that this scene is written to a separate file, and indicates the file name infix for that
* `f:scene` maps to the id in the [generic list of scenes](https://github.com/faustedition/faust-web/blob/master/data/scene_line_mapping.js)
* `f:scene-label` contains the label from the generic list of scenes
* similar for `f:act` and `f:act-label`.

Currently, `f:section` is written to second-level divs (if the document exceeds a certain maximum size), and `f:scene` / `f:act` and their corresponding labels are determined by matching (1) `n` attributes or, if that doesn't help, verse numbers to the scene mapping also used for the bar graph. If this doesn't work, we need new rules that work globally. If we cannot easily derive new rules from the existing markup that match what you want, we'll have to adjust the markup.

It is not helpful to discuss this only for specific examples, and I do not consider it a good idea to write too many exceptions or scene-specific rules into the stylesheets. Maybe talk about this on friday.

**Comment by gerritbruening** [comment] 2016-07-25 15:42
Yes, let's talk about this on friday!

**Comment by thvitt** [comment] 2016-11-17 21:08
I think this is fixed in the 2nd beta …

**Closed by thvitt** 2016-11-17 21:08 UTC
Labels: gen-html
